from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from Locators.location import location
from Locators.location import base
import time

class addToCart:
    def addToCart_01(self):
        lc = location()
        bs = base()
        self.driver = bs.driver
        driver = self.driver
        driver.maximize_window()
        driver.get(bs.url)
        driver.implicitly_wait(3)
        time.sleep(3)
        driver.find_element(By.XPATH, lc.myAccount).click()
        time.sleep(1)
        driver.find_element(By.XPATH, lc.login).click()
        time.sleep(1)
        driver.implicitly_wait(3)
        driver.find_element(By.XPATH, lc.email).send_keys("anishnepal62@gmail.com")
        driver.find_element(By.XPATH, lc.password).send_keys("fortnight45269")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,300)")
        driver.find_element(By.XPATH, lc.loginbutton).click()
        driver.implicitly_wait(10)
        driver.find_element(By.XPATH, '//*[@id="logo"]/a/img').click()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="content"]/div[2]/div[1]/div/div[3]/button[1]').click()
        wait = WebDriverWait(driver, 10)
        wait.until(EC.visibility_of_element_located((By.XPATH, '/html/body/div[2]/div[1]')))
        time.sleep(2)
        driver.quit()

    def addToCart_02(self):
        lc = location()
        bs = base()
        self.driver = bs.driver
        driver = self.driver
        driver.maximize_window()
        driver.get(bs.url)
        driver.implicitly_wait(3)
        time.sleep(3)
        driver.find_element(By.XPATH, lc.myAccount).click()
        time.sleep(1)
        driver.find_element(By.XPATH, lc.login).click()
        time.sleep(1)
        driver.implicitly_wait(3)
        driver.find_element(By.XPATH, lc.email).send_keys("anishnepal62@gmail.com")
        driver.find_element(By.XPATH, lc.password).send_keys("fortnight45269")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,300)")
        driver.find_element(By.XPATH, lc.loginbutton).click()
        driver.implicitly_wait(10)
        driver.find_element(By.XPATH, '//*[@id="logo"]/a/img').click()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="content"]/div[2]/div[1]/div/div[3]/button[1]').click()
        wait = WebDriverWait(driver, 10)
        wait.until(EC.visibility_of_element_located((By.XPATH, '/html/body/div[2]/div[1]')))
        time.sleep(1)
        driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/a[2]').click()
        driver.implicitly_wait(10)
        driver.quit()

    def addToCart_03(self):
        lc = location()
        bs = base()
        self.driver = bs.driver
        driver = self.driver
        driver.maximize_window()
        driver.get(bs.url)
        driver.implicitly_wait(3)
        time.sleep(3)
        driver.find_element(By.XPATH, lc.myAccount).click()
        time.sleep(1)
        driver.find_element(By.XPATH, lc.login).click()
        time.sleep(1)
        driver.implicitly_wait(3)
        driver.find_element(By.XPATH, lc.email).send_keys("anishnepal62@gmail.com")
        driver.find_element(By.XPATH, lc.password).send_keys("fortnight45269")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,300)")
        driver.find_element(By.XPATH, lc.loginbutton).click()
        driver.implicitly_wait(10)
        driver.find_element(By.XPATH, '//*[@id="logo"]/a/img').click()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="content"]/div[2]/div[1]/div/div[3]/button[1]').click()
        wait = WebDriverWait(driver, 10)
        wait.until(EC.visibility_of_element_located((By.XPATH, '/html/body/div[2]/div[1]')))
        time.sleep(1)
        driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/a[2]').click()
        driver.implicitly_wait(10)
        driver.quit()

    def addToCart_04(self):
        lc = location()
        bs = base()
        self.driver = bs.driver
        driver = self.driver
        driver.maximize_window()
        driver.get(bs.url)
        driver.implicitly_wait(3)
        time.sleep(3)
        driver.find_element(By.XPATH, lc.myAccount).click()
        time.sleep(1)
        driver.find_element(By.XPATH, lc.login).click()
        time.sleep(1)
        driver.implicitly_wait(3)
        driver.find_element(By.XPATH, lc.email).send_keys("anishnepal62@gmail.com")
        driver.find_element(By.XPATH, lc.password).send_keys("fortnight45269")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,300)")
        driver.find_element(By.XPATH, lc.loginbutton).click()
        driver.implicitly_wait(10)
        driver.find_element(By.XPATH, '//*[@id="logo"]/a/img').click()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="content"]/div[2]/div[1]/div/div[3]/button[1]').click()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        time.sleep(1)
        driver.find_element(By.XPATH, '//*[@id="content"]/div[2]/div[2]/div/div[3]/button[1]').click()
        wait = WebDriverWait(driver, 10)
        wait.until(EC.visibility_of_element_located((By.XPATH, '/html/body/div[2]/div[1]')))
        time.sleep(5)
        driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/a[2]').click()
        driver.implicitly_wait(10)
        driver.quit()
